# Generated by Django 4.1.4 on 2023-05-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='temail',
            field=models.EmailField(max_length=30),
        ),
    ]
